#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the sockMerchant function below.
def count(ar,i):
    kekka = 0
    for j in ar:
        if i==j:
            kekka +=1
    return kekka

def sockMerchant(n, ar):
        kekka = 0
        Nlist = []
        for i in set(ar):
            temp = count(ar,i)
            Nlist.append(temp)
        for i in Nlist:
            kekka += i//2
        return    kekka
        

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    ar = list(map(int, input().rstrip().split()))

    result = sockMerchant(n, ar)

    fptr.write(str(result) + '\n')

    fptr.close()
